version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true